name: Release
on:
    push:
        branches:
            - master
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cache Packages
              id: cache-packages
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install dependencies
              if: steps.cache-packages.outputs.cache-hit != 'true'
              run: npm ci
            - name: Build
              run: |
                  npm run build
                  npm run scully
            - name: Deploy Github Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist/static
